### ISSUE TITLE
Connection hijacking in secondary regions must take forking servers into account

### ISSUE THREAD

**Issue by jsierles** [superfly/fly-ruby#12]
Forking servers like puma in cluster mode, or unicorn, might include code like this:

```ruby
  on_worker_boot do
    ActiveRecord::Base.establish_connection if defined?(ActiveRecord)
  end
```

This conflicts with our attempt to automatically hijack the database connection. We should either hook directly into these servers, or warn about this and ensure people add the correct calls into the Fly gem on boot.

**Comment by jsierles** [comment]
This is a problem even on servers that do not include code like the above. We need to hook into the initialization cycle earlier to fix the problem.

**Comment by jsierles** [comment]
See:

`ActiveSupport.on_load(:active_record)`

https://github.com/bensheldon/good_job/blob/7bf31c04fb5fe9d015ac0f6dcb975a8872ef6e99/lib/good_job/railtie.rb#L36-L59

https://github.com/bensheldon/good_job/blob/f6aa754da39922812dd4939ba6159c20a6f93b0d/spec/support/postgres_notices.rb#L8

**Comment by jsierles** [comment]
@jonathanhefner Based on your other PRs, I wondered: would working on this be interesting to you? Right now this library is unstable for use with more than one worker because of this.

**Comment by jonathanhefner** [comment]
> ```ruby
>   on_worker_boot do
>     ActiveRecord::Base.establish_connection if defined?(ActiveRecord)
>   end
> ```
>
> This conflicts with our attempt to automatically hijack the database connection.

Since Rails 5.2, that kind of code should not be necessary.  See https://github.com/rails/rails/pull/29807#issuecomment-350422552.  In particular, https://github.com/rails/rails/pull/31241 removed the above code from the `config/puma.rb` template.  Also note that Rails 5.2 is no longer supported, even for severe security issues, [as of 2022-06-01](https://guides.rubyonrails.org/v7.0.3/maintenance_policy.html#severe-security-issues).

But it's possible that upgraded apps still have that kind of config code lying around.  (And I'm not sure what Fly's policy is for unsupported versions of Rails...?)  I've attempted to address the issue #18.

> This is a problem even on servers that do not include code like the above.

What kind of behavior are you seeing in those cases?

**Comment by jsierles** [comment]
I'm not concerned that much about old apps. The problem is that this behavior exhibits even with no such code. I believe it's because we're hooking into initialization at the wrong time. The links above look like the 'correct' way to do it. This is easy to reproduce by running puma with a worker concurrency of 2 or more.

The behavior is that we don't end up hijacking the database config correctly, so writes just raise errors.

**Comment by jonathanhefner** [comment]
From testing locally, the sequences of events is:

1. `on_worker_fork` / `on_worker_boot` blocks run if not using Puma's `--preload` flag.
2. The `fly.regional_database` initializer from #18 would run.
3. The [`active_record.initialize_database` initializer](https://github.com/rails/rails/blob/v7.0.3/activerecord/lib/active_record/railtie.rb#L271-L280) runs.
    * Note that if an application is using Active Record at all, `ActiveRecord` will be defined by this point.  (`on_load(:active_record)` applies to `ActiveRecord::Base` rather than `ActiveRecord`.)
4. The current `fly.regional_database` initializer runs.
5. `to_prepare` blocks run.
    * If an application is using Active Record at all, [`if defined?(ActiveRecord)`](https://github.com/superfly/fly-ruby/blob/ef8a9f6ccad291e8951cc3c8c4dcf4ad936112bd/lib/fly-ruby/railtie.rb#L9) should always be true at this point.
6. Eager loading happens if `config.eager_load` is true.  `on_load(:active_record)` blocks run.
7. `after_initialize` blocks run.
8. `on_worker_fork` / `on_worker_boot` blocks run if using Puma's `--preload` flag.
9. Requests come in.
10. `on_load(:active_record)` blocks run if `config.eager_load` is false.
11. Connection "before checkout" callbacks run.
    * At this point, the connection is already established and in hand, so overriding with the regional database settings is not possible.

Based on the above, replacing `if defined?(ActiveRecord)` with `on_load(:active_record)` could work, however:

* It relies on our initializer running after `active_record.initialize_database`.  Initializers are topologically sorted with an unstable sort, so we would need to add `after: "active_record.initialize_database"` or an `after_initialize` block to guarantee this order.

* More specifically, it relies on our `on_load(:active_record)` block running after [the `establish_connection` call](https://github.com/rails/rails/blob/v7.0.3/activerecord/lib/active_record/railtie.rb#L278) in `active_record.initialize_database`'s `on_load(:active_record)` block.  If the implementation of `active_record.initialize_database` changes or its `establish_connection` call is further delayed, the problem may reemerge.

* If user code calls `establish_connection` for any reason, such as in an (obsolete) `on_worker_boot` block, the problem will still occur.

Therefore, I believe #18 is a more robust solution.  By overriding `DATABASE_URL` before `active_record.initialize_database` runs, we ensure that the regional database settings will be picked up by [`ActiveRecord::Base.configurations`](https://github.com/rails/rails/blob/v7.0.3/activerecord/lib/active_record/railtie.rb#L276).  Thus any `establish_connection` call (without args) will target the regional database, whether from Rails or user code.

But my knowledge of Fly's architecture is limited, and I am still unclear on why `DATABASE_URL` does not already point to the regional database when `FLY_REGION` does.

(Sidenote: I believe the issue that https://github.com/bensheldon/good_job/blob/7bf31c04fb5fe9d015ac0f6dcb975a8872ef6e99/lib/good_job/railtie.rb#L36-L59 addresses is fixed by https://github.com/rails/rails/pull/45476.)

**Comment by jsierles** [comment]
Nice sleuthing! #18 sounds like the best option then. As mentioned in the other PR comment, `DATABASE_URL` is just set across the entire app as an 'app secret', where `FLY_REGION` is set by the platform directly. Do sign up for Fly and I'll add some credits to your org for testing.
